In [8]:
import pandas as pd

In [9]:
file = 'TodosLosDatos.csv'
df = pd.read_csv(file, sep=';', encoding='utf-8', header=None)
df.head()

c:\Users\esosa\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3442: DtypeWarning: Columns (9,164,165,169,170) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,0,1,2,3,4,5,6,7,8,9,...,170,171,172,173,174,175,176,177,178,179
0,aaa-195-2018-00,4.0,0.0,0.0,NaN,NaN,2018-07-10,2018-07-18,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,aaa-264-2020-00,3.0,0.0,1.0,1.0,NaN,2020-05-09,2020-05-21,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,aaa-264-2020-01,3.0,0.0,0.0,NaN,NaN,2020-10-22,2020-10-23,1.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,aaa-306-2019-00,1.0,0.0,0.0,NaN,NaN,2019-05-13,2019-05-21,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4,aaa-437-2018-00,1.0,0.0,0.0,NaN,NaN,2018-06-21,2018-06-27,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [10]:
df[12].describe

<bound method NDFrame.describe of 0       38.0
1       38.0
2       38.0
3        NaN
4       38.0
        ...
6667    38.0
6668    38.0
6669    38.0
6670     NaN
6671    42.0
Name: 12, Length: 6672, dtype: float64>